project:
  type: website
  output-dir: "/Users/bcdemattei/Desktop/Projects/winter-ice/docs"

website:
  title: "Winter Limnology Network"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - wschool.qmd
      - collabs.qmd
      
  page-footer: 
    center: "Background Image of Frozen Lake Credit: [Kuhnmi](https://commons.wikimedia.org/wiki/File:Alps_of_Switzerland_Frozen_Lake_at_Bernina_Ospitz_%2824152193174%29.jpg#filelinks)"
             
              

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: white



